config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :categories
  devise_for :users
  resources :products
  resource :shopping_cart
  root 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  # devise :database_authenticatable, :trackable, :timeoutable, :lockable 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image 
    belongs_to :category
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
    acts_as_shopping_cart

  def taxes
    0 #Update this to add tax
   end
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ApplicationRecord
    acts_as_shopping_cart_item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :create, :update, :edit, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end

    def authenticate_admin!
      authenticate_user!
      redirect_to :root, status: :forbidden unless current_user.admin?
    end 
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :create, :update, :edit, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @categories = Category.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new 
    
  end

  # GET /products/1/edit
  def edit
    
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image, :category_id)
    end

    def authenticate_admin!
      authenticate_user!
      redirect_to :root, status: :forbidden unless current_user.admin?
    end    
    
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
    before_action :extract_shopping_cart
    before_action :authenticate_user!
  
    def create
      @product = Product.find(params[:product_id])
      @shopping_cart.add(@product, @product.price)
      redirect_to shopping_cart_path
    end
  
    def show
    end
    
    def destroy
      @shopping_cart.clear
      redirect_to shopping_cart_path
    end
  
    private
    def extract_shopping_cart
      shopping_cart_id = session[:shopping_cart_id]
      @shopping_cart = session[:shopping_cart_id] ? ShoppingCart.find(shopping_cart_id) : ShoppingCart.create
      session[:shopping_cart_id] = @shopping_cart.id
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>


<h3> Products under this category </h3>
<% Product.where(category_id: @category.id).each do |product| %>
<li> <%= product.name %> </li>
<% end %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
     <%= link_to 'Buyit', root_path, class: "navbar-item" %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
     
     <% if current_user.try(:admin?) %>
      <%= link_to 'New Product', new_product_path, class:"navbar-item" %>
      <%= link_to 'New Category', new_category_path, class:"navbar-item" %>
     <% end %>


      <%= link_to 'Cart', shopping_cart_path, class:"navbar-item" %>



      <div class="navbar-item has-dropdown is-hoverable">
        
          <%= link_to "Categories", categories_path, class: "navbar-link" %>
        

        <div class="navbar-dropdown">
          <% Category.all.each do |category| %>
            <%= link_to category.name, category_path(category), class: "navbar-item" %>
          <% end %>
        </div>
      </div>





    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
                 
        <% if user_signed_in? %>
          <%= link_to 'Edit Account', edit_user_registration_path, class: "button is-info" %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class:"button is-light" %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>     
        <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buyit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="section">
<%= simple_form_for(@product) do |f| %>

    <% if @product.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
            <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


    <div class="field">
        <div class="control">
            <%= f.input :name, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'}%>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.input :description, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'}%>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.input :price, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'}%>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category"} %>
            
        </div>
    </div>

    <div class="field">
        <h4>Upload an image (this is required):</h4>
        <%= f.input :image, label: false %>
    </div>


<%= f.button :submit, class: 'button is-primary' %>

<% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="instrument-index-grid pt4">
  <% @products.each do |product| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
        <figure class="image is-3by2">
          <%= link_to (image_tag(product.image)), product, class:'img-responsive' if product.image.attached? %> 
        </figure>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%=link_to product.name, product %></h3>

      <p class="has-text-gray fg pt1">Specs: <%= product.description %></p>
      <p><%= link_to Category.find(product.category_id).name, category_path(product.category_id) %></p>
      <p><%= number_to_currency(product.price) %></p>
      <%= link_to 'Add to cart', shopping_cart_path(:product_id => product), :method => 'POST', class: "button is-info" %>
      
      <% if current_user.try(:admin?) %>
      <%= link_to 'Edit', edit_product_path(product) %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<figure class="image is-square">
  <%= link_to (image_tag(@product.image)), @product, class:'img-responsive' if @product.image.attached? %> 
</figure>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
<%= link_to 'Add to cart', shopping_cart_path(:product_id => @product), :method => 'POST' %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shopping_carts/_shopping_cart_item.html.erb
<div>
  <div><%= shopping_cart_item.item.name %></div>
  <div><%= shopping_cart_item.item.price %></div>
  <hr>
</div>
 

app/views/shopping_carts/show.html.erb
<h1>Shopping Cart</h1>

<%= render :partial => 'shopping_cart_item', :collection => @shopping_cart.shopping_cart_items %>

<div>
  <div><b>Total:</b><%= number_to_currency @shopping_cart.total %></div>
   <%= link_to 'Clear Cart', @shopping_cart, method: :delete, data: { confirm: 'Are you sure?' } %>